Import('env')

import copy
import buildTools
import setupTools

includes = [
]

dependencies = [
    'config'
]

env_config_test = env.Clone()

sources = Glob('src/*.cpp')
unittest = buildTools.createUnittest(env_config_test, 'config-unittest', sources, includes, dependencies, None, dependencies)
