Import('env')

import copy
import buildTools
import setupTools

includes = [
    '{rootDir}/config/include'.format(rootDir = env['BUILD_DIR'])
]

dependencies = [
]

env_config_test = env.Clone()

sources = Glob('src/*.cpp')
unittest = buildTools.createUnittest(env_config_test, 'config-unittest', sources, includes, dependencies, None, dependencies)
