OPTIMIZATION_LEVEL_0 = 0
OPTIMIZATION_LEVEL_1 = 1
OPTIMIZATION_LEVEL_2 = 2
OPTIMIZATION_LEVEL_3 = 3
OPTIMIZATION_LEVEL_DEBUG = OPTIMIZATION_LEVEL_0

WARNING_LEVEL_NONE = 0
WARNING_LEVEL_SOME = 1
WARNING_LEVEL_ALL = 2

CXX_VERSION_03 = 0
CXX_VERSION_11 = 1

MULTI_THREADING_OFF = 0
MULTI_THREADING_PTHREAD = 1
MULTI_THREADING_OPENMP = 2


