version: 0.6.0-{build}

os:
    - Visual Studio 2019

platform:
    - x64
    - x86

configuration:
    - release
    - debug

environment:
    APPVEYOR_RDP_PASSWORD: Blaat0

install:
    # - meson   # Pre-installed by app veyor
    # - cmake   # Pre-installed by app veyor
    # - git     # Pre-installed by app veyor
    # - boost   # Pre-installed by app veyor
    - cinst ninja
    #- cinst nsis
    #- ps: (new-object System.Net.WebClient).DownloadFile('https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip', "$($pwd)/envar.zip")     # Retrieve NSIS EnVar plugin
    #- ps: Expand-Archive "$($pwd)/envar.zip" -DestinationPath "${Env:ProgramFiles(x86)}/NSIS"   # Install NSIS EnVar plugin

build_script:
    - echo %CONFIGURATION%
    - "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat\" %PLATFORM%"
    - set BOOST_ROOT="C:/local/boost_1_73_0"
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    - meson setup --buildtype %CONFIGURATION% --prefix %cd%/install -D api-documentation=false -D usage-documentation=false -D changelog=false -D terminate-on-assert=false -D test=false -D "plugins-prefix=C:\\Program Files\\exec-helper" -D "version=%APPVEYOR_BUILD_VERSION%" -D "copyright=Copyright (c) 2020 Bart Verhagen"  build .
    - meson compile -C build
    - meson install -C build --no-rebuild
    #- copy installer.nsi install
    #- copy LICENSE install
    #- cd install
    #- makensis installer.nsi
    #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    - cd ..

on_failure:
    - appveyor PushArtifact build

artifacts:
    - path: install\installer.exe
      name: installer

    - path: install
      name: install
      type: zip
