Import('env')

import copy
import buildTools
import setupTools

includes = [
    '../stubs',
    '../include',
]

dependencies = [
    'core',
    'plugins'
]

env_core_test = env.Clone()
setupTools.noIgnoredAttribute(env_core_test)

sources = Glob('src/*.cpp')
unittest = buildTools.createUnittest(env_core_test, 'plugins-unittest', sources, includes, dependencies, None, dependencies)
