Import('env')

import copy
import buildTools
import setupTools

includes = [
    '../../yaml/include',
    '../include',
]

dependencies = [
    'yaml'
]

env_yaml_test = env.Clone()

sources = Glob('src/*.cpp')
unittest = buildTools.createUnittest(env_yaml_test, 'yaml-unittest', sources, includes, dependencies, None, dependencies)

install_files = env_yaml_test.Install('test/yaml/', 'test.yaml') 
bin = env.Alias("unittest", install_files)
bin = env.Alias("test", install_files)
