Import('env')

import copy
import buildTools
import setupTools

includes = [
    '../stubs',
    '{rootDir}/log/include'.format(rootDir = env['BUILD_DIR'])
]

dependencies = [
    'commander',
    'testutils'
]

env_commander = env.Clone()

sources = Glob('src/*.cpp')
unittest = buildTools.createUnittest(env_commander, 'commander-unittest', sources, includes, dependencies, None, dependencies)
