Import('env')

import copy
import buildTools
import setupTools

includes = [
    '../include',
    '../stubs'
]

dependencies = [
    'commander'
]

env_commander = env.Clone()

sources = Glob('src/*.cpp')
unittest = buildTools.createUnittest(env_commander, 'commander-unittest', sources, includes, dependencies, None, dependencies)
