Import('env')

import copy
import buildTools
import setupTools

dependencies = [
    'core'
]

env_core = env.Clone()
setupTools.noIgnoredAttribute(env_core)

sources = ['exec-helper.cpp']
buildTools.createProgram(env, 'exec-helper', sources, None, dependencies, None, env['BIN_DIR'], dependencies)
