Import('env')

import copy
import buildTools
import setupTools

includeUsageRequirements = [ 
    '{rootDir}/config/include'.format(rootDir = env['BUILD_DIR'])
]

includes = [
    'include/config',
    includeUsageRequirements
]

dependencies = [
]

libUsageRequirements = [ 
]

libs = [
    libUsageRequirements,
]

env_config = env.Clone()
setupTools.noIgnoredAttribute(env_config)

sources = Glob('src/*.cpp')
buildTools.createLib(env_config, 'config', sources, includes, env, includeUsageRequirements, libUsageRequirements, None, dependencies)
