Import('env')

import copy
import buildTools
import setupTools

includeUsageRequirements = [ 
    '{rootDir}/core/include'.format(rootDir = env['BUILD_DIR'])
]

includes = [
    'include/core',
    '{rootDir}/log/include'.format(rootDir = env['BUILD_DIR']),
    includeUsageRequirements
]

dependencies = [
    'yaml'
]

libUsageRequirements = [ 
    'boost_program_options',
    dependencies
]

libs = [
    libUsageRequirements,
]

env_core = env.Clone()
setupTools.noIgnoredAttribute(env_core)

sources = Glob('src/*.cpp')
buildTools.createLib(env_core, 'core', sources, includes, env, includeUsageRequirements, libUsageRequirements, None, dependencies)
