Import('env')

import copy
import buildTools
import setupTools

includeUsageRequirements = [ 
    '{rootDir}/core/include'.format(rootDir = env['BUILD_DIR']),
    '{rootDir}/yaml/include'.format(rootDir = env['BUILD_DIR']),
]

includes = [
    'include/core',
    includeUsageRequirements,
    env['BUILD_DIR'] + '/config/include'
]

libUsageRequirements = [ 
    'boost_program_options',
    'yaml'
]

libs = [
    libUsageRequirements
]

libs_path = [
    env['LIBS_DIR'],
    env['THIRD_PARTY_LIBS_DIR'],
]

env_core = env.Clone()
setupTools.noIgnoredAttribute(env_core)

env_core['CPPPATH'].extend(includes)

sources = Glob('src/*.cpp')
buildTools.createLib(env_core, 'core', sources, includes, env, includeUsageRequirements, libUsageRequirements)
