Import('env')

includes = [
]

libs = [
]

libs_path = [
]

env_example = env.Clone()
sources = ['example.cpp']
target = env_example.Program(source = sources)
target = env.Install(env['BIN_DIR'], target) 
env.Alias('example', target)

env_unittest = env.Clone()
sources = ['example-unittest.cpp']
target = env_unittest.Program(source = sources)
target = env.Install(env['BIN_DIR'] + '/test/unittest', target) 
env.Alias('example-unittest', target)
