Import('env')

import copy
import buildTools
import setupTools

yaml_env = env.Clone()
yaml_includeUsageRequirements = [ 
    env['BUILD_DIR'] + '/yaml/include',
]

yaml_includes = [
    'include/yaml',
    env['THIRD_PARTY_DIR'] + '/yaml-cpp/include',
    env['BUILD_DIR'] + '/log/include',
    yaml_includeUsageRequirements
]

dependencies = [
    'config'
]

yaml_libUsageRequirements = [ 
    'yaml-cpp',
    dependencies
]

yaml_libs_path = [
    env['LIBS_DIR'],
    env['THIRD_PARTY_LIBS_DIR'],
]

#setupTools.disableWarningAsError(yaml_env)
setupTools.disableShadowWarnings(yaml_env)

yaml_sources = Glob('src/*.cpp')
buildTools.createLib(yaml_env, 'yaml', yaml_sources, yaml_includes, env, yaml_includeUsageRequirements, yaml_libUsageRequirements, None, dependencies)
