Import('env')

folders = [
    'catch/SConscript',
    'config/SConscript',
    'yaml/SConscript',
    'core/SConscript',
    'plugins/SConscript',
    'commander/SConscript',
    'test/SConscript',
    'applications/SConscript'
]

SConscript(folders)
