Import('env')

import copy
import buildTools
import setupTools

includes = [
    'include',
    '../include',
    '../stubs',
    '{rootDir}/log/include'.format(rootDir = env['BUILD_DIR'])
]

dependencies = [
    'core',
    'testutils'
]

env_core_test = env.Clone()
setupTools.noIgnoredAttribute(env_core_test)

sources = Glob('src/*.cpp')
unittest = buildTools.createUnittest(env_core_test, 'core-unittest', sources, includes, dependencies, None, dependencies)
